id: A472E5B4A
title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
type: translation
pechas:
- I602C6548
- I3B9BCB9A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:15:41.034970
  last_modified_at: 2023-01-04 12:15:41.034979
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I602C6548/0735: 4EAC
  I3B9BCB9A/0B9B: 4EAC
